#!/bin/bash


# Build variables
WORKING="working"
OUTPUT="output"
SOURCE="archlive"
LIVEROOT="airootfs"
CONFIG="jovarkos-config"

function generic_error() {
    echo "Incorrect syntax or options. Please use the 'help' flag for more information."
}

function error_no-archiso() {
	if [ ! -d "$SOURCE" ]; then
            echo "Please select profile to build upon: "
            echo "    releng (Used in Official Monthly Builds)"
            echo "    baseline (Minimal live configuration)"
            read -p "Profile: " profile
	    profile "$profile"
        fi
}

function build_iso() {
    error_no-archiso
    echo "Clearing $WORKING directory before beginning..."
    sudo rm -rf $WORKING
    echo "Copying $CONFIG/archlive to $(pwd)..."
    sudo cp $CONFIG/archlive . -r
    sudo /usr/bin/mkarchiso -v -w $WORKING -o $OUTPUT $SOURCE
}

function run_iso() {
    /usr/bin/run_archiso -i $OPTARG
}

function profile() {
    cp -r "/usr/share/archiso/configs/$OPTARG/" $SOURCE
    echo "Copied profile $OPTARG to $SOURCE"
}

function version() {
    echo "JovarkOS ISO build script v2022.04.18.r5"
}

function usage() {
    __usage="Usage: ./build_iso.sh [FLAGS] [OPTIONS]
    Options:
    -b, build                     Clean working directory and build fresh ISO image using defaults from the $SOURCE/profiledef.sh file
    -r, run <path to iso>         Run ISO image
    -p, profile <profile name>    Create new profile using the specified profile name
    -h, help                      Print this help message
    -v, version                   Get the version of this script
    
    Options for '-p' and 'profile':
    Profile - see <https://wiki.archlinux.org/title/Archiso#Prepare_a_custom_profile>
    for more information
         - Use either 'releng' (Used in Official Monthly Builds) or 'baseline' (Minimal live configuration) as the profile name. 
         - Profiles live in the /usr/share/archiso/configs/ directory. "
    echo "$__usage"
}


while getopts "br:p:hv" opt
do
    case $opt in
        b)
            build_iso ;;
        r)
            run_iso $OPTARG ;;
        p)
            profile $OPTARG ;;
        h)
            usage ;;
        v)
            version ;;
        \?)
            echo "Invalid option: $OPTARGS" >&2
            exit 1 ;;
        *)
            echo "Option $opt requires an argument." >&2
            exit 1 ;;
    esac
done
