#!/bin/bash


# Build variables
WORKING="working"
OUTPUT="output"
SOURCE="archlive"
LIVEROOT="airootfs"
ISO="jovarkos-$(date +%Y.%m.%d)-x86_64.iso"

function generic_error() {
    echo "Incorrect syntax or options. Please use the 'help' flag for more information."
}

function build_iso() {
    sudo /usr/bin/mkarchiso -v -w $WORKING -o $OUTPUT $SOURCE
}

function run_iso() {
    /usr/bin/run_archiso -i $OPTARG
}

function profile() {
    cp -r "/usr/share/archiso/configs/$OPTARG/" $SOURCE
    echo "Copied profile $OPTARG to $SOURCE"
}

function version() {
    echo "JovarkOS ISO build script v2022.03.25.r3"
}

function usage() {
    __usage="Usage: ./build_iso.sh [FLAGS] [OPTIONS]
    Options:
    -b, build                     Build fresh ISO image using defaults from the $SOURCE/profiledef.sh file
    -r, run <path to iso>         Build and run fresh ISO image
    -p, profile <profile name>    Clean working directory and create 
    -h, help                      Print this help message
    -v, version                   Get the version of this script
    
    Options for '-p' and 'profile':
    Profile - see <https://wiki.archlinux.org/title/Archiso#Prepare_a_custom_profile>
    for more information
         - Use either 'releng' (Used in Official Monthly Builds) or 'baseline' (Minimal live configuration) as the profile name. 
         - Profiles live in the /usr/share/archiso/configs/ directory. "
    echo "$__usage"
}


while getopts "br:p:hv" opt
do
    case $opt in
        b)
            build_iso ;;
        r)
            run_iso $OPTARG ;;
        p)
            profile $OPTARG ;;
        h)
            usage ;;
        v)
            version ;;
        \?)
            echo "Invalid option: $OPTARGS" >&2
            exit 1 ;;
        *)
            echo "Option $opt requires an argument." >&2
            exit 1 ;;
    esac
done
